final String CREATE_TABLE_USUARIO =
    "CREATE TABLE usuario (id INTEGER PRIMARY KEY AUTOINCREMENT, email VARCHAR(100) NOT NULL, firstName VARCHAR(100) NOT NULL,  lastName VARCHAR(100) NOT NULL, password VARCHAR(100) NOT NULL)";
